version: '3.8'

services:
  web:
    build: .
    container_name: my_php_apache_dev

    ports:
      # Прокидаємо порт 80 контейнера на порт 8080 вашого комп'ютера
      - "8080:80"
    volumes:
      # Монтуємо вашу папку з кодом всередину контейнера
      - ./public/public:/var/www/html
      - ./php_errors.ini:/usr/local/etc/php/conf.d/php_errors.ini
    restart: always
